### ISSUE TITLE
DML training implementation

### ISSUE THREAD

**Issue by aryanasadianuoit** [DefangChen/OKDDip#2]
Hi. I Just tried to re-implement both regular knowledge distillation and also DML training. Unfortunately, None of these methods outperform the accuracy of the model that has been trained from scratch. Would you please share your results?

**Comment by DefangChen** [comment]
Please provide email address and I will send my training logs to you.

**Comment by aryanasadianuoit** [comment]
Hi, Please use the email in my profile. I appreciate your help.

**Comment by DefangChen** [comment]
I have send the results to you, please check the email.
