### ISSUE TITLE
Why you use so infrequent networks?

### ISSUE THREAD

**Issue by JiyueWang** [DefangChen/OKDDip#5]
Why you use WRN-20-8 instead of the official WRN-16-8 or 28-10? Does your model work with deeper networks on CIFAR100, like WRN-28-10 or PyramidNet200?

**Comment by DefangChen** [comment]
Just randomly selection. The reason for using WRN-20-8 possibly based on a certain repository or paper. I didn't try deeper network due to the limited time and GPU resources.
