### ISSUE TITLE
Where can I find the appendix of your latest aaai'21 paper?

### ISSUE THREAD

**Issue by zxhr2793** [DefangChen/OKDDip#6]
In your latest semckd paper, you mentioned that your experimental settings are described in technical appendix. But it is online unavaliable. Would you please update it in your arxiv paper? 

Meanwhile, I find that the compared results of other methods in table 1 are higher than the reported and evaluated results using the open-source database. Which changes do you make to promote these methods? Thanks.

**Comment by DefangChen** [comment]
Thanks for asking. We will update the arXiv version as soon as possible. We have released our code as well as the implementation of compared approaches at https://github.com/DefangChen/SemCKD. I guess it is enough for reproducibility.

**Comment by zxhr2793** [comment]
> Thanks for asking. We will update the arXiv version as soon as possible. We have released our code as well as the implementation of compared approaches at https://github.com/DefangChen/SemCKD. I guess it is enough for reproducibility.

Ok, thank you.
