### ISSUE TITLE
Question regarding how it works

### ISSUE THREAD

**Issue by hxu38691** [DefangChen/OKDDip#7]
Hi, 

thank you for the innovative resonance it brought to me, I really like the idea but have some questions as well,

1. since choose which peer to distill from is an option for optimization, in this case how to prevent each model from just drawing close to peers of the same kind to minimize the distillation loss? Would it just be the opposite of increasing diversity, and prone more and more to the “deep mutual learning” with sharper attention scores? Is this effect(sharper attention scores) ever observed when you conduct experiments? 

2. when trying to escalate the ensemble size by evolution, how do you think of the idea of transfering the trained “group leader” to a new group(with noobies) and iteratively apply the same process with no BP for the old leader? there are 3 sub questions i am concerning.
    1. whether there will be non-trivial performance gap if no training for the “old leader” in the new group
    2. should i replace “group leader” with unrolling of all peers? does it matter?
    3. would it be a better idea of initializing new group member with “old leader” weights? would it hurt diversity?

Thank you.

**Comment by DefangChen** [comment]
Hi, 

​For your first question, as shown in Equation (11), each peer will gradually stop learning from others. The individual learning in the subsequent stage will provide additional room for maintaining the diversity. 

​For the second subquestion in your second question, as discussed in ablation study section, the performance will decrease if the group leader is replaced by another peer. I did not conduct experiments about your two subquestions, but it is worth a try. If I understand correctly,  you want to combine the idea of "ICML18: Born-Again Neural Networks" to see what will happen. 

Thanks.

**Comment by hxu38691** [comment]
Yes, My ultimate goal is to use evolution-KD process(like born-again NN) to replace ensemble with adaptive importance at each stage(which the optimal weights depend on N ensemble and settings etc.), so that by using adaptive peer KD

rolling(train([peer_n, peer_n+1])) can replace train([peer_1, peer_2, ...N]) together,

do you see any constraint of applying this method, 
can they achieve similar diversity?

**Comment by DefangChen** [comment]
Actually, I have obtained some primary results on the BAN-like distillation for a working paper, which is different from your above questions. If you are interested, you can email me with cv or homepage, and then we can discuss in detail.
